name: Build and Deploy SampleAzureWebApi to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # or '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./SampleAzureWebApi/SampleAzureWebApi.csproj

      - name: Build
        run: dotnet build ./SampleAzureWebApi/SampleAzureWebApi.csproj --no-restore --configuration Release

      - name: Publish
        run: dotnet publish ./SampleAzureWebApi/SampleAzureWebApi.csproj -c Release -o ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: samplewebapi2025
          slot-name: production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ./publish
